sudo: required
services:
  - docker

node_js:
  - "11.10.1"

before_install:
  - docker build -t ashukhard/docker-react -f Dockerfile.dev .

script:
  - docker run ashukhard/docker-react npm run test -- --coverage
